language: python
sudo: false  # enable container-based build

stages:
  - test
  - name: deploy
    if: tag IS present OR branch == master

# matrix:
#   include:
#     - python: 2.7
#       env: TOXENV=py2

#     - python: 3.4
#       env: TOXENV=py3
#     - python: 3.5
#       env: TOXENV=py3
#     - python: 3.6
#       env: TOXENV=py3

python:
  - 2.7
  - 3.6

install: pip install wheel twine tox coveralls

script:
  - export TOXENV=py`echo $TRAVIS_PYTHON_VERSION | tr "." "\n" | head -n 1`
  - echo $TOXENV
  - tox

jobs:
  include:
    - stage: deploy
      python: 3.6
      script:
        - python setup.py bdist_wheel
        - twine upload dist/*.whl -u $DEPLOY_USER -p $DEPLOY_PASS
# before_deploy:
#   - python setup.py bdist_wheel

# deploy:
#   provider: pypi
#   user: $DEPLOY_USER
#   password: $DEPLOY_PASS
#   distributions: "bdist_wheel"
#   on:
#     # tags: true
#     python: 3.6
# after_success:
#   script:
#     - stage: deploy
#       script:
#         - python setup.py bdist_wheel
#         - twine upload dist/*.whl -u $DEPLOY_USER -p $DEPLOY_PASS
      # if: tag IS present
      # python: 3.6


#after_success:
#  - coveralls