anguage: python
sudo: false  # enable container-based build
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

install:
  - pip install tox twine wheel
  #- pip install coveralls

script:
  - export PYVER=`echo $TRAVIS_PYTHON_VERSION | tr "." "\n" | head -n 1`
  - echo $PYVER
  - tox -e py$PYVER

jobs:
  include:
    - stage: package
      python: 3.5
      script:
      - python setup.py bdist_wheel
      - twine upload dist/*.whl -u $DEPLOY_USER -p $DEPLOY_PASS

#after_success:
#  - coveralls