language: python
sudo: false  # enable container-based build

matrix:
  include:
    - python: 2.7
      env: TOXENV=py2

    - python: 3.4
      env: TOXENV=py3
    - python: 3.5
      env: TOXENV=py3
    - python: 3.6
      env: TOXENV=py3

install:
  - pip install wheel twine tox coveralls

script:
  - tox

deploy:
  provider: script
  script:
    - python setup.py bdist_wheel
    - twine upload dist/*.whl -u $DEPLOY_USER -p $DEPLOY_PASS
  on:
    # tags: true
    python: 3.6
#after_success:
#  - coveralls