anguage: python
sudo: false  # enable container-based build

matrix:
  include:
    - python: 2.7
      env: TOXENV=py2

    - python: 3.3
      env: TOXENV=py3
    - python: 3.4
      env: TOXENV=py3
    - python: 3.5
      env: TOXENV=py3
    - python: 3.6
      env: TOXENV=py3

install:
  - pip install wheel
  - pip install twine
  - pip install tox
  #- pip install coveralls

jobs:
  include:
    - stage: package
      python: 3.5
      script:
      - python setup.py bdist_wheel
      - twine upload dist/*.whl -u $DEPLOY_USER -p $DEPLOY_PASS

#after_success:
#  - coveralls