language: python

python:
  - 3.5
  - 3.7
  - 3.8
  #- pypy3.5

install:
  - pip install tox tox-factor wheel python-coveralls

script:
  - echo $TRAVIS_PYTHON_VERSION
  - export PYVER=`echo $TRAVIS_PYTHON_VERSION | tr "." "\n" | head -n 1 | sed 's/^py//'`
  - echo $PYVER
  - tox -f py$PYVER

# Deploy to test.pypi.org for branches
# Deploy to pypi.org for tags
# NOTE: You can not replace builds published to pypi, even if you delete one
#       so you must make sure your versions are always unique
jobs:
  include:
    - stage: deploy-release
      python: 3.7
      script:
        - pip install twine
        - python setup.py bdist_wheel
        - twine upload dist/*.whl -u $DEPLOY_USER -p $DEPLOY_PASS
      if: tag IS true
    - stage: deploy-snapshot
      python: 3.7
      script:
        - pip install twine
        - python setup.py bdist_wheel
        - twine upload --repository-url https://test.pypi.org/legacy/
            dist/*.whl -u $DEPLOY_USER -p $DEPLOY_PASS
      if: tag IS NOT true

after_success:
  - coveralls
