version: 2.1

orbs:
  # https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@1.3.2

jobs:
  build:
    docker:
      - image: cimg/python:3.6.13
    steps:
      - checkout
      - run:
          # have to update pip before running the install-packages
          # orb because of a bug in the cryptographic library
          # https://github.com/pyca/cryptography/issues/5771
          name: Update pip
          command: pip install --upgrade pip
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
          pypi-cache: true
      - run:
          name: analyse
          command: |
            python -m tox --sitepackages -e py3-lint
      - run:
          name: test
          command: |
            python -m tox --sitepackages -e py3-test -- --block-network --junit-xml ./build/junit.xml
            coveralls
            python -m tox --sitepackages -e py3-docs
      - store_test_results:
          path: build/
      - run:
          name: package
          command: |
            python setup.py bdist_wheel
      - run:
          name: deploy
          command: |
            [[ -z "${CIRCLE_TAG}" ]] && REPO_URL="--repository-url https://test.pypi.org/legacy/"
            twine upload ${REPO_URL} ./dist/*.whl -u $PYPI_DEPLOY_USER -p $PYPI_DEPLOY_PASS

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context:
            - PUBLISHING
          filters:
            tags:
              # NOTE: we can't run builds for every tag
              # because pre-release builds generate tags
              # and we don't want an infinite loop building
              # against those tags
              only: /^\d+\.\d+\.\d+$/

